# Generated by Django 5.2.17 on 2026-09-23 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_filingsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('LEGAL', 'Documento Legal / Contractual'), ('POLIZA', 'Pólizas y Seguros'), ('SERVICIOS', 'Servicios Públicos'), ('FINANCIERO', 'Facturación y Pagos'), ('COMUNICACION', 'Comunicaciones y Solicitudes')], default='LEGAL', max_length=30)),
                ('requires_expiration', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo Documental',
                'verbose_name_plural': 'Tipos Documentales',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de Radicado')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('source_channel', models.CharField(choices=[('FISICO_ESCANEADO', 'Documento Físico Escaneado'), ('DIGITAL_INTERNO', 'Digital Cargado por Personal'), ('PORTAL_WEB', 'Radicado por Cliente en Portal Web'), ('CORREO', 'Ingreso por Correo Electrónico')], default='DIGITAL_INTERNO', max_length=30)),
                ('processing_status', models.CharField(choices=[('RECIBIDO', 'Recibido / En cola'), ('PROCESANDO', 'Procesando en Celery'), ('REQUIERE_REVISION', 'Requiere Validación Humana (HITL)'), ('PROCESADO', 'Clasificado y Archivado'), ('FALLIDO', 'Error de Procesamiento')], db_index=True, default='RECIBIDO', max_length=30)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttype')),
            ],
            options={
                'verbose_name': 'Documento Radicado',
                'verbose_name_plural': 'Documentos Radicados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processing_status', '-created_at'], name='doc_status_created_idx')],
            },
        ),
    ]
